### ISSUE TITLE
How to ignoring certain types of error?

### ISSUE THREAD

**Issue by HouCoder** [jamesseanwright/valimate#10]
I'm using lazy-load in my website, the `img` tag is like this:

```html
<img data-lazy="/avatar/default.png" alt="Default avatar" />
```
What I want is ignoring all missing `src` attribute errors and showing the rest of validation errors.

Thanks.

**Comment by jamesseanwright** [comment]
Unfortunately, as the Nu Validator API only provides basic error messages and traces, it's impossible to reliably determine a type of error; one could search the message string, but I'd heavily advise against this as this could change at any time.

This suggests that it would definitely be worthwhile to expose errors and warnings directly when one uses Valimate programmatically; you'll then be able to ignore the errors in your own project and update when the messages change, which means that Valimate would not break.

I'll investigate this and ultimately release it as 3.0.0. For the time being, you could use an [inline SVG](https://stackoverflow.com/questions/5775469/whats-the-valid-way-to-include-an-image-with-no-src) as the default value for `src` attributes.

Let me know if you have any questions.

Cheers,
James

**Comment by HouCoder** [comment]
Many thanks for your excellent response. 👍
