### ISSUE TITLE
Feature requests - Exclude error & basic auth

### ISSUE THREAD

**Issue by stuartjnelson** [jamesseanwright/valimate#11]
Hi @jamesseanwright,

Awesome package, thanks for sharing! Really easy to use and nice simple docs too. I was wondering about the following features;

- Is it possible to test a website that has basic authentication?
- Is it possible to exclude specific lines or rules for a specific URL or all URLs in the config file?

Cheers!

**Comment by jamesseanwright** [comment]
Hey @stuartjnelson 

Really sorry it took me a while to get back to you; this got lost amongst a flurry of notifications.

> Is it possible to test a website that has basic authentication?

I think this would be a great addition. I have some downtime next week so I'll tackle this accordingly.

> Is it possible to exclude specific lines or rules for a specific URL or all URLs in the config file?

I've had a [similar request](https://github.com/jamesseanwright/valimate/issues/10) previously and am against adding exceptions for particular rules; given Valimate is a simple proxy for a remote Nu validator endpoint, it is unaware of any rules or deeper validation. I also think that ignoring particular line numbers would be brittle, as I imagine they would change fairly often.

One solution I have, however, would be to order specific _nodes_, based upon common CSS selectors; if a blacklist is specified, Valimate would:

1. parse the DOM
2. filter the nodes that match the particular selectors
3. serialise the new DOM
4. send the markup to the Nu validator.

It'd look something like:

```json
{
  "ignoredNodes": [
    ".social-metadata",
    "#analytics-block"
  ]
}
```

Would something like this work for you?

**Comment by jamesseanwright** [comment]
Closed due to inactivity.
