### ISSUE TITLE
Webpack Dev Server and Rewrites

### ISSUE THREAD

**Issue by titantwentyone** [jamesseanwright/valimate#13]
Thanks for this plugin. Works great.

One issue I did come across was that valimate bugs out when accessing a "pretty url" using the webpack dev-server and rewrites. My dev server config:

```
    devServer: {
        port:9000,
        index: 'index.htm',
        host: 'mysite.local',
        contentBase: path.join(__dirname, 'dist'),
        publicPath: '/',
        watchContentBase: true,
        historyApiFallback: {
            rewrites: [
                {from: /^\/$/, to: '/index.htm'},
                {from: /^\/about/, to: '/about.htm'},
            ]
        }
    },
```

While trying to validate some urls I found the following with my valimate.json:
```
{
        "urls": [
                "http://mysite.local:9000/", <-- this validates
                "http://mysite.local:9000/about.htm", <-- this is fine also
                "http://mysite.local:9000/about/" <-- this causes the error below
        ]
}
```
`http://mysite.local:9000/about/` renders fine in a browser so I know the rewrite is in effect.

 Error reported:

```
Error: Request to  failed with HTTP undefined
    at Request._callback (/var/www/local/mysite/node_modules/valimate/lib/services/httpService.js:26:13)
    at Request.self.callback (/var/www/local/mysite/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/var/www/local/mysite/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/var/www/local/mysite/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1244:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
To  clarify, I am spinning up the dev server in one terminal so the site is running locally and then running valimate in a different terminal. Since the html is pulled from GET request rather than reading the file on disk, I would have expected this to run okay? This is more of a "curio" than anything else as I can use the `.htm` locations to validate.

**Comment by titantwentyone** [comment]
Interestingly, when routing these through Express, the validation works. Not sure if this helps.

**Comment by jamesseanwright** [comment]
Hey @titantwentyone,

Thanks for raising this! I'll take a deeper look this evening and get back to you.

**Comment by titantwentyone** [comment]
If I can help in any way - testing any fix, workaround etc. please let me know. It's not a critical issue for me at all and easily circumvented.

**Comment by jamesseanwright** [comment]
Sorry for the lack of response! I'm going to investigate and hopefully release a fix at the weekend.

**Comment by jamesseanwright** [comment]
Hey @titantwentyone,

Sorry for the delayed response. By setting the `verbose` property to `true` on Webpack Dev Server's `historyApiFallback` option (WDS simply uses [`connect-history-api-fallback`](https://github.com/bripkens/connect-history-api-fallback) under the hood), I was able to see that WDS was rejecting Valimate's requests as it wasn't sending an `Accept` header; I was able to fix the issue by providing one.

Please can you upgrade to `valimate@3.0.2` when you can and confirm if it resolves the issue for you?

**Comment by jamesseanwright** [comment]
In fact, I'll close this now; please reopen it if you're still having issues.

**Comment by titantwentyone** [comment]
Thank you so much for looking into this. Works perfectly. Nice clean urls now! If you need a hand in the future with this, ping me. Plan on using this with every project so more than happy to help if I can.

**Comment by jamesseanwright** [comment]
Sounds good. Cheers!
