### ISSUE TITLE
How to simply validate a HTML string?

### ISSUE THREAD

**Issue by nise** [jamesseanwright/valimate#14]
How can I simply validate a HTML string? Such a basic example would help people to start and test valimate.

**Comment by jamesseanwright** [comment]
Although I could introduce this behaviour, Valimate isn't designed to validate arbitrary input strings of HTML, and instead explicitly requests the URLs present in the configuration in order to validate _their_ markup. Is there anything in particular you're trying to achieve with Valimate?

**Comment by jamesseanwright** [comment]
Closed due to inactivity.
