### ISSUE TITLE
Escape valiation for `link rel="apple-touch-icon"`

### ISSUE THREAD

**Issue by Nguonchhay** [jamesseanwright/valimate#6]
I see the 'https://validator.w3.org/nu/' has fixed this issue `link rel="apple-touch-icon"` . Check this link: https://github.com/validator/validator/issues/433?#issuecomment-268984493.

When will your package update that feature because currently, it still report as error.

**Comment by jamesseanwright** [comment]
Hey,

I have just tried this locally and it works fine. Here's the markup against which I tested Valimate:

```
<!DOCTYPE html>
<html>
    <head>
        <title>Apple Touch Test</title>            
        <meta charset="utf-8" />
        <link rel="apple-touch-icon" sizes="180x180" href="/assets/img/favicons/apple-touch-icon.png?1482192202570" />
    </head>

    <body>
        <h1>Test</h1>
        <p>Content</p>
    </body>
</html>
```

Please note that Valimate is simply a CLI that consumes a remote validation backend, the default being https://validator.w3.org/nu/; Valimate contains no explicit validation logic, so any backend changes should work out of the box.

What is the markup that you're sending to the validator?

**Comment by Nguonchhay** [comment]
I run a test with a real website in my company. Let me check the result again that the original `valimate` command provide.
