### ISSUE TITLE
Should allow multiple import fonts from CDN

### ISSUE THREAD

**Issue by Nguonchhay** [jamesseanwright/valimate#8]
Current, when I import multiple fonts from Google, it displays an error:

`Bad value “http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800|Shadows+Into+Light” for attribute “href” on element “link”: Illegal character in query: “|” is not allowed. - Line 7, Column 218`.

Could you ignore this error? I can separate the calling fonts but it will increase the number of HTTP request.

**Comment by jamesseanwright** [comment]
Hi,

I could add a new property to the `valimate.json` config file that specifies which rules should be ignored, but this won't be a simple change; I need to determine how the Nu validator uniquely identifies rules in order for them to be ignorable.

I'll do some research when I have time next week and let you know my findings.

**Comment by jamesseanwright** [comment]
Hi @Nguonchhay,

It just occurred to me that you can encode the pipe character:

```
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light" />
```

This validates successfully.

Thanks,
James
